import type { League } from './football-types';

export const FOOTBALL_LEAGUES: League[] = [
  {
    id: 'lpf',
    name: 'LPF (Arg)',
    level: 1,
    teams: [
      { id: 'lpf1', name: 'Riber Plate', strength: 55 },
      { id: 'lpf2', name: 'Boca Nuniors', strength: 54 },
      { id: 'lpf3', name: 'Racing Club', strength: 52 },
      { id: 'lpf4', name: 'Independiente', strength: 50 },
      { id: 'lpf5', name: 'San Lorenzo', strength: 49 },
      { id: 'lpf6', name: 'Estudiantes', strength: 48 },
      { id: 'lpf7', name: 'Velez', strength: 47 },
      { id: 'lpf8', name: 'Argentinos Jrs', strength: 46 },
      { id: 'lpf9', name: 'Newell\'s', strength: 45 },
      { id: 'lpf10', name: 'Rosario Central', strength: 44 },
      { id: 'lpf11', name: 'Lanus', strength: 43 },
      { id: 'lpf12', name: 'Godoy Cruz', strength: 42 },
      { id: 'lpf13', name: 'Defensa y Justicia', strength: 42 },
      { id: 'lpf14', name: 'Talleres', strength: 41 },
      { id: 'lpf15', name: 'Gimnasia', strength: 40 },
      { id: 'lpf16', name: 'Huracan', strength: 40 },
      { id: 'lpf17', name: 'Union', strength: 39 },
      { id: 'lpf18', name: 'Colon', strength: 38 },
      { id: 'lpf19', name: 'Banfield', strength: 38 },
    ],
  },
  {
    id: 'seriea',
    name: 'Serie A',
    level: 2,
    teams: [
      { id: 'sa1', name: 'Inter Milan', strength: 70 },
      { id: 'sa2', name: 'AC Milan', strength: 69 },
      { id: 'sa3', name: 'Juventus', strength: 68 },
      { id: 'sa4', name: 'Napoli', strength: 66 },
      { id: 'sa5', name: 'AS Roma', strength: 65 },
      { id: 'sa6', name: 'Lazio', strength: 64 },
      { id: 'sa7', name: 'Atalanta', strength: 63 },
      { id: 'sa8', name: 'Fiorentina', strength: 62 },
      { id: 'sa9', name: 'Torino', strength: 60 },
      { id: 'sa10', name: 'Bologna', strength: 59 },
      { id: 'sa11', name: 'Sassuolo', strength: 58 },
      { id: 'sa12', name: 'Udinese', strength: 57 },
      { id: 'sa13', name: 'Monza', strength: 56 },
      { id: 'sa14', name: 'Empoli', strength: 55 },
      { id: 'sa15', name: 'Salernitana', strength: 54 },
      { id: 'sa16', name: 'Lecce', strength: 53 },
      { id: 'sa17', name: 'Hellas Verona', strength: 52 },
      { id: 'sa18', name: 'Cremonese', strength: 51 },
      { id: 'sa19', name: 'Sampdoria', strength: 50 },
    ],
  },
  {
    id: 'ligue1',
    name: 'Ligue 1',
    level: 3,
    teams: [
      { id: 'l1-1', name: 'Paris SG', strength: 80 },
      { id: 'l1-2', name: 'Marseille', strength: 75 },
      { id: 'l1-3', name: 'AS Monaco', strength: 74 },
      { id: 'l1-4', name: 'RC Lens', strength: 73 },
      { id: 'l1-5', name: 'Lille OSC', strength: 72 },
      { id: 'l1-6', name: 'Stade Rennais', strength: 71 },
      { id: 'l1-7', name: 'Olympique Lyon', strength: 70 },
      { id: 'l1-8', name: 'OGC Nice', strength: 68 },
      { id: 'l1-9', name: 'FC Lorient', strength: 66 },
      { id: 'l1-10', name: 'Stade de Reims', strength: 65 },
      { id: 'l1-11', name: 'Clermont Foot', strength: 64 },
      { id: 'l1-12', name: 'Montpellier', strength: 63 },
      { id: 'l1-13', name: 'Toulouse FC', strength: 62 },
      { id: 'l1-14', name: 'FC Nantes', strength: 61 },
      { id: 'l1-15', name: 'Stade Brestois', strength: 60 },
      { id: 'l1-16', name: 'AJ Auxerre', strength: 59 },
      { id: 'l1-17', name: 'ESTAC Troyes', strength: 58 },
      { id: 'l1-18', name: 'AC Ajaccio', strength: 57 },
      { id: 'l1-19', name: 'Angers SCO', strength: 56 },
    ],
  },
  {
    id: 'bundesliga',
    name: 'Bundesliga',
    level: 4,
    teams: [
      { id: 'b1', name: 'Bayern Munich', strength: 88 },
      { id: 'b2', name: 'Borussia Dortmund', strength: 85 },
      { id: 'b3', name: 'RB Leipzig', strength: 84 },
      { id: 'b4', name: 'Union Berlin', strength: 82 },
      { id: 'b5', name: 'SC Freiburg', strength: 80 },
      { id: 'b6', name: 'Bayer Leverkusen', strength: 79 },
      { id: 'b7', name: 'Eintracht Frankfurt', strength: 78 },
      { id: 'b8', name: 'VfL Wolfsburg', strength: 77 },
      { id: 'b9', name: 'FSV Mainz 05', strength: 76 },
      { id: 'b10', name: 'Bor. M\'gladbach', strength: 75 },
      { id: 'b11', name: '1. FC Köln', strength: 74 },
      { id: 'b12', name: 'TSG Hoffenheim', strength: 73 },
      { id: 'b13', name: 'Werder Bremen', strength: 72 },
      { id: 'b14', name: 'VfL Bochum', strength: 71 },
      { id: 'b15', name: 'FC Augsburg', strength: 70 },
      { id: 'b16', name: 'VfB Stuttgart', strength: 69 },
      { id: 'b17', name: 'Hertha BSC', strength: 68 },
      { id: 'b18', name: 'FC Schalke 04', strength: 67 },
      { id: 'b19', name: 'Arminia Bielefeld', strength: 66 },
    ],
  },
    {
    id: 'laliga',
    name: 'La Liga',
    level: 5,
    teams: [
      { id: 'll1', name: 'Real Madrid', strength: 92 },
      { id: 'll2', name: 'FC Barcelona', strength: 91 },
      { id: 'll3', name: 'Atlético Madrid', strength: 88 },
      { id: 'll4', name: 'Real Sociedad', strength: 86 },
      { id: 'll5', name: 'Villarreal CF', strength: 85 },
      { id: 'll6', name: 'Real Betis', strength: 84 },
      { id: 'll7', name: 'Athletic Club', strength: 83 },
      { id: 'll8', name: 'Sevilla FC', strength: 82 },
      { id: 'll9', name: 'CA Osasuna', strength: 80 },
      { id: 'll10', name: 'Celta de Vigo', strength: 79 },
      { id: 'll11', name: 'Rayo Vallecano', strength: 78 },
      { id: 'll12', name: 'Girona FC', strength: 77 },
      { id: 'll13', name: 'RCD Mallorca', strength: 76 },
      { id: 'll14', name: 'Valencia CF', strength: 75 },
      { id: 'll15', name: 'Getafe CF', strength: 74 },
      { id: 'll16', name: 'UD Almería', strength: 73 },
      { id: 'll17', name: 'Cádiz CF', strength: 72 },
      { id: 'll18', name: 'Real Valladolid', strength: 71 },
      { id: 'll19', name: 'Elche CF', strength: 70 },
    ],
  },
  {
    id: 'premier',
    name: 'Premier League',
    level: 6,
    teams: [
      { id: 'pl1', name: 'Manchester City', strength: 98 },
      { id: 'pl2', name: 'Liverpool', strength: 96 },
      { id: 'pl3', name: 'Chelsea', strength: 94 },
      { id: 'pl4', name: 'Arsenal', strength: 93 },
      { id: 'pl5', name: 'Manchester Utd', strength: 92 },
      { id: 'pl6', name: 'Tottenham', strength: 90 },
      { id: 'pl7', name: 'Newcastle Utd', strength: 88 },
      { id: 'pl8', name: 'West Ham', strength: 86 },
      { id: 'pl9', name: 'Brighton', strength: 85 },
      { id: 'pl10', name: 'Aston Villa', strength: 84 },
      { id: 'pl11', name: 'Leicester City', strength: 83 },
      { id: 'pl12', name: 'Crystal Palace', strength: 82 },
      { id: 'pl13', name: 'Wolves', strength: 81 },
      { id: 'pl14', name: 'Everton', strength: 80 },
      { id: 'pl15', name: 'Leeds United', strength: 79 },
      { id: 'pl16', name: 'Southampton', strength: 78 },
      { id: 'pl17', name: 'Brentford', strength: 77 },
      { id: 'pl18', name: 'Fulham', strength: 76 },
      { id: 'pl19', name: 'Nottingham Forest', strength: 75 },
    ],
  },
];
